### ISSUE TITLE
Multiple subtitle on the video 

### ISSUE THREAD

**Issue by kaito-kaito** [SunnyLi/videojs-ass#10]
Hi there. Thanks for the useful plugin. 
How can I put multiple ASS subtitle on one video with switcher on the video control bar? 
Thanks

**Comment by SunnyLi** [comment]
Unfortunately, that may not be possible with the current implementation.
To load a different subtitle file, for now you'll have to reload the player and provide a different file URL during the plugin initialization.

Although you *might* (not sure if it's really doable) be able to load up several subtitles on one instance of videojs if you duplicate the plugin to have several different names (duplicate [this](https://github.com/SunnyLi/videojs-ass/blob/70e0900bf908f5c8b0669d9567e3517df6ccceb4/src/videojs.ass.js#L132) line and make each line have a different name) and load each duplicated plugin with different subtitle file.. but that'll have some performance penalties..

**Comment by kaito-kaito** [comment]
I see. Any way, thanks for the plugin and thanks for your time. I found a way to load more than one subtitle :)

**Comment by hrk** [comment]
@kaito-kaito care to share? :)

**Comment by yousef31** [comment]
@kaito-kaito can you please tell me the way to load multiple subtitles

**Comment by SunnyLi** [comment]
You can now switch subtitles via the API. (there isn't an UI for it yet)
See [here](https://github.com/SunnyLi/videojs-ass/commit/4548378156565f230f6f1c64fa7b20a65baa363d#diff-62ad28cc71ae9a54a611bc2d551533f6L36) for detail.
