### ISSUE TITLE
Subtitle Not Correctly display on different browsers

### ISSUE THREAD

**Issue by pasathaioum5** [SunnyLi/videojs-ass#13]
Let the picture tell everything.

![untitled](https://cloud.githubusercontent.com/assets/9591497/17885805/fe18b21a-6948-11e6-8ae0-eb7eb9a228a8.png)

Did I do something wrong?

**Comment by SunnyLi** [comment]
I can't say.. maybe try to disable Svg as I recently saw some issues
with that on Firefox and maybe that's also the case for IE.

```
plugins: {
  ass: {
    src: 'subs/subtitles.ass',
    enableSvg: false
  }
}
```

**Comment by pasathaioum5** [comment]
Thanks for your advice
My Subtitle is now showing but unfortunately...

![untitled2](https://cloud.githubusercontent.com/assets/9591497/17922376/d7739c90-6a08-11e6-9881-b345b95c7284.png)

**Comment by SunnyLi** [comment]
I think it is an issue with how each browser handle fonts.

See [here](https://stackoverflow.com/questions/4698564/fonts-looks-different-in-firefox-and-chrome) for potential solutions.

**Comment by pasathaioum5** [comment]
Problem solved by "enableSvg: false" and declare @font-face for all the font I've used at CSS file
although it not perfect but does the job
Thank you

**Comment by SunnyLi** [comment]
glad you got it working :)
