### ISSUE TITLE
How to insert a subtitle link?

### ISSUE THREAD

**Issue by Vampireos** [SunnyLi/videojs-ass#14]
hi, prompt and have the opportunity to insert into the subtitles link?
..and highlight the subtitle text with the cursor like a regular text

**Comment by SunnyLi** [comment]
hello,

> prompt and have the opportunity to insert into the subtitles link?

I think you want to ask the user to provide subtitle link and then load it?
Well, it doesn't have this feature, but it should be possible to have a prompt external to videojs but have some logic to reinitialize the videojs player with updated subtitle link inserted into the plugin config.

> highlight the subtitle text with the cursor like a regular text

You can do it by removing `pointer-events: none;` in `.vjs-ass` class [here](https://github.com/SunnyLi/videojs-ass/blob/96426b1db06fc54bac9ee733a73b6c0eafaccd54/src/videojs.ass.css#L8) or just  overwrite the style with
```
.vjs-ass {
  pointer-event: auto
}
```

**Comment by SunnyLi** [comment]
Seems like I've misunderstood what you meant by `subtitles link`
but it looks like you've already got your answer at Arnavion/libjass#82.
