### ISSUE TITLE
Cannot toggle subtitle display on touch devices

### ISSUE THREAD

**Issue by adgoncal** [SunnyLi/videojs-ass#15]
I am using videojs 5.12.6 and cannot toggle the subtitle display on touch devices. You can test it on Chrome's device emulation.

You are listening to click events, but other videojs buttons actually listen to tap, focus and blur in addition to click:
https://github.com/videojs/video.js/blob/v5.12.6/src/js/clickable-component.js#L27

Also, other videojs buttons simply extend the Button Class with the `handleClick` and `buildCSSClass` methods instead of calling `this.on('click')` and `this.addClass` on the constructor.
Example:
https://github.com/videojs/video.js/blob/v5.12.6/src/js/control-bar/play-toggle.js#L39
https://github.com/videojs/video.js/blob/v5.12.6/src/js/control-bar/play-toggle.js#L30

Suggestion:
```diff
   constructor: function (player, options) {
     options.name = options.name || 'assToggleButton';
     VjsButton.call(this, player, options);
-
-    this.addClass('vjs-ass-button');
-
-    this.on('click', this.onClick);
   },
-  onClick: function () {
+  buildCSSClass: function () {
+    var classes = VjsButton.prototype.buildCSSClass.call(this);
+    return 'vjs-ass-button ' + classes;
+  },
+  handleClick: function () {
     if (!this.hasClass('inactive')) {
       this.addClass('inactive');
       overlay.style.display = "none";
```

**Comment by SunnyLi** [comment]
Hey, thanks for the suggestion.

Unfortunately, I'm a bit too busy recently.
I can't take a proper look at this until the winter break starts :/

**Comment by SunnyLi** [comment]
Your changes worked great so I've committed it as is.

Also, prior to this commit, I found that a click event will be fired on
mobile device if you press and hold on the toggle for ~2 seconds.

Thanks for the help.
