### ISSUE TITLE
Incompatibility with minified versions of videojs

### ISSUE THREAD

**Issue by Teranode** [SunnyLi/videojs-ass#2]
any version above this one gives off errors

**Comment by SunnyLi** [comment]
Any specific error you are getting?

Anyways I'll look into it now.

**Comment by ChristianMcQuilkin** [comment]
is it only suppose to be specifically working with youtube videos? Ive tried replicating the same build as you have y building libjass but when i use it i get some error relating to libjass + renderer-null unexpected length

**Comment by SunnyLi** [comment]
> is it only suppose to be specifically working with youtube videos?

No, you can probably use any provider.
I used the YouTube provider because the video I need is there.

> Am i to use the dev version of videojs or the normal version

Yeah, you'll have to use the `dev` version.. until videojs/video.js#1586 gets resolved. :innocent:

> Ive tried replicating the same build as you have y building libjass but when i use it i get some error relating to libjass + renderer-null unexpected length.

are you on the latest version which I've just pushed less than an hour ago?
how did you get the source? bower/npm/git

**Comment by ChristianMcQuilkin** [comment]
i think the the 2nd issue you mentioned might be the problem. And ill build the newest one now and test it.

**Comment by ChristianMcQuilkin** [comment]
Alright that seems to have worked. I just wish i didnt have to use the dev version because i want to minify it.

**Comment by SunnyLi** [comment]
Glad to hear that you got it working. :smiley: 

Actually, you can in fact use the minified version videojs with the current version of this plugin
(I've tested it just now) although the show/hide subtitle button will no longer work.

You can disable the show/hide subtitle button by setting the option:

    plugins: {
      ass: {
        'src': "some_subtitle.ass",
        'button': false
      }
    }

**Comment by ChristianMcQuilkin** [comment]
Meh ill just live with the dev version for now. Would you like to see how
i've implemented it?
Because im wondering if it would be possible to have the button for
multilangual purposes.

**Comment by SunnyLi** [comment]
I think you'll need to modify this plugin quite a bit if you need it to load multiple subtitle files
but it is definitely possible.

I'm not planning to add more features to this plugin at the moment,
but if you got something great working feel free to submit a pull request.

**Comment by ChristianMcQuilkin** [comment]
Well the only thing i've managed to do was make it work with a responsive
videojs player that has a 16:9 aspect ration whenever the browser resizes
or when ur on a phone. It's just some small css edit in lijass.css though
and removing the "px" in the video.ass.js

**Comment by Sita-** [comment]
Teranode, are you able to supply those fixes? It may help me with my problem on mobile and responsive player.

**Comment by SunnyLi** [comment]
Hi, I've updated the plugin to support minified version of `videojs 5.x`.

Just so you know. :smile:
