### ISSUE TITLE
what about JavascriptSubtitlesOctopus?

### ISSUE THREAD

**Issue by anoosi** [SunnyLi/videojs-ass#20]
Hi,
videojs-ass and libjass it's very good but still there some bugs in libjass
recently i tried to use JavascriptSubtitlesOctopus https://github.com/Dador/JavascriptSubtitlesOctopus
it's work like charm on videojs and no bugs at all in rendering ass files, like vlc exactly !!
but i just need a toggle to make the subtitle off/on like videojs at least for now!
can anyone make a costume button to do that ?
i using same this ex https://dador.github.io/JavascriptSubtitlesOctopus/videojs.html

another thing, is there any plan to work on JavascriptSubtitlesOctopus in videojs-ass plugin ?
just like libjass lib, i think add JavascriptSubtitlesOctopus to a second choice would be great!

thanks ..

**Comment by SunnyLi** [comment]
Good suggestion. I'll consider it for future updates.
