### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Love656** [SunnyLi/videojs-ass#22]
.

**Comment by SunnyLi** [comment]
Yes, see [here](https://github.com/SunnyLi/videojs-ass/blob/a884c6b8fcc8bab9e760214bb551601f54cd769f/example.html#L58).

or use [this fork](https://github.com/AviiNL/videojs-ass) which lets you specify all subtitle files on first load.

**Comment by ahmad2012a78s0** [comment]
if  can add multiple subtitles on a single video or, not

**Comment by SunnyLi** [comment]
It can only display one subtitle track at a time.
Only the selected subtitle track will be displayed.

**Comment by ahmad2012a78s0** [comment]
For example I have subtitle , en , ar , jp
Can the viewer navigate between subtitle without any problems?

**Comment by SunnyLi** [comment]
Yes, that shouldn't be a problem.

**Comment by ahmad2012a78s0** [comment]
YOU K SEND Example?
