### ISSUE TITLE
Use libjass.ASS.fromUrl ?

### ISSUE THREAD

**Issue by Arnavion** [SunnyLi/videojs-ass#6]
Any particular reason you do [this](https://github.com/SunnyLi/videojs-ass/blob/3704f6c/src/videojs.ass.js#L72-L76)

```javascript
subsRequest = new XMLHttpRequest()
...
subsRequest.open("GET", options.src, true);
subsRequest.addEventListener("load", function () {
    var assPromise = libjass.ASS.fromString(
    subsRequest.responseText,
    libjass.Format.ASS
);
...
subsRequest.send(null);
```

instead of just

```javascript
var assPromise = libjass.ASS.fromUrl(options.src, libjass.Format.ASS);
```

? Is there something wrong with fromUrl that you can't use it?

**Comment by SunnyLi** [comment]
I didn't know that it can do that :open_mouth:
thanks for the heads up, I'll update it.
